Feature/coins list
alirezatahani/coinbase pull request #17
Opened 2022-10-22 11:10 UTC by behzadiv

2022-10-22 12:08 UTC, alirezatahani requested changes

2022-10-22 12:08 UTC, alirezatahani0 commented on src/components/coinsList/content/AddToFavorite.tsx
> +    price: string;
move to types file

2022-10-22 12:08 UTC, alirezatahani0 commented on src/components/coinsList/content/AddToFavorite.tsx
> +  const coin = props;
destruct from component definition

2022-10-22 12:08 UTC, alirezatahani0 commented on src/components/coinsList/content/AddToFavorite.tsx
> +  const { favoriteList } = useSelector((state: any) => state.FavoriteReducer);
order of usage 

1. custom hooks 
2. states
3. functions
4. hooks

2022-10-22 12:08 UTC, alirezatahani0 commented on src/components/coinsList/content/CoinChangePrice.tsx
> +    <CoinPositiveChange>+{priceChange}</CoinPositiveChange>
clean this lines 

if (priceChange === null) return {something}

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/content/CoinListContainer.tsx
> +          }) => {
move interfaces to types file

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/content/CoinListContainer.tsx
> +                <CoinPriceSection props={coin.price} />
pass props as specific name

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/content/CoinListContainer.tsx
> +                  <img src={coin.iconUrl} style={{ width: 40 }} />
destruct values from coin to simpler usage

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/content/CoinPrice.tsx
> +import { formatPrice } from "../utils/formatPrice";
move numberToPrice to general utils

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/styles/coinListContainer_style.ts
> +  color: "white",
use from theme

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/styles/coinPrice_style.ts
> +export interface CoinPriceProps {
move to types file

2022-10-22 12:08 UTC, alirezatahani commented on src/components/coinsList/utils/formatPrice.ts
> +export const formatPrice = (price: number) => {
change name to numberToPrice

2022-10-23 06:46 UTC, behzadiv commented on src/components/coinsList/content/AddToFavorite.tsx
> +    price: string;
done!

2022-10-23 06:47 UTC, behzadiv commented on src/components/coinsList/content/AddToFavorite.tsx
> +  const coin = props;
done

2022-10-23 11:57 UTC, alirezatahani requested changes

2022-10-23 11:57 UTC, alirezatahani commented on src/components/coinsList/content/CoinList.tsx
> +            <CoinContent key={uuid}>
create a component from it 
Coin, CoinItem

2022-10-23 11:57 UTC, alirezatahani commented on src/components/coinsList/content/AddToFavorite.tsx
> +  const { favoriteList } = useSelector((state: any) => state.FavoriteReducer);
dont use any

2022-10-23 11:57 UTC, alirezatahani commented on src/components/coinsList/styles/coinPriceChange_style.ts
> +export const CoinNegetiveChange = styled.p(({ theme }) => ({
merge it with positive

2022-10-23 11:57 UTC, alirezatahani commented on src/components/coinsList/content/CoinChangePrice.tsx
> +  return priceChange.includes("-") ? (
change to use JS Number functions

2022-10-23 11:57 UTC, alirezatahani commented on src/components/coinsList/content/CoinPrice.tsx
> +import { formatPrice } from "../../../utils/numberToPrice";
add path to tsConfig

2022-10-23 11:57 UTC, alirezatahani commented on src/modules/getCoinsData/content/getCoinsData.tsx
> +import useFetch from "../../../hooks/useFetch";
add to tsConfig Path

2022-11-02 11:34 UTC, alirezatahani approved these changes

2022-11-02 11:35 UTC, merged